#pragma once

namespace Engine
{

	enum SOUNDID 
	{
		SINGLE, MULTY, SOUNDID_END
	};
	enum RENDERSTATE
	{
		RENDERSTATE_NOCULLSOLID, RENDERSTATE_CULLSOLID, RENDERSTATE_WIREFRAME, RENDERSTATE_END
	};

	enum GEOMETRYTYPE
	{
		GT_SPHERE, GT_CAPSULE, GT_BOX, GT_TRIANGLEMESH, GT_CONVEX, GT_COUNT, GT_END
	};

	enum TRANSFORMTYPE 
	{ 
		TS_VIEW, TS_PROJ, TS_END 
	};

	enum AXIS
	{
		AXIS_X, AXIS_Y, AXIS_Z, AXIS_END
	};

	enum FONTTYPE
	{ 
		ARIAL, BAZZI , CULIM, DIGIT, KYOBO, HYEMIN, FONT_END
	};

	enum STATE 
	{ 
		STATE_RIGHT, STATE_UP, STATE_LOOK, STATE_POSITION, STATE_END 
	};

	enum COLLIDERTYPE 
	{ 
		TYPE_AABB, TYPE_OBB, TYPE_SPHERE, TYPE_END 
	};

	enum LAYERMASK
	{
		LAYER_PLAYER, LAYER_MONSTER, LAYER_OBSTACLE, LAYER_GROUND, LAYER_WALL, LAYER_UI, LAYER_DEFAULT ,LAYER_END
	};

	enum SORTLAYERTYPE 
	{ 
		SORTLAYER_UI, SORTLAYER_OBJ, SORTLAYER_END 
	};

	enum VALUETYPE
	{
		VAL_INT, VAL_FLOAT, VAL_DOUBLE, VAL_UINT, VAL_END
	};

	enum DATATYPE
	{
		DATATYPE_MAP, DATATYPE_MONSTER, DATATYPE_PLAYER, DATATYPE_OBJECT, DATATYPE_BOSS, DATATYPE_GROUND, DATATYPE_WALL, DATATYPE_END
	};

	enum class QUERYTYPE
	{
		NONE = 0,
		SIMULATION = 1 << 0,
		TRIGGER = 1 << 1,
		ALL = SIMULATION | TRIGGER
	};
}